name: Publish distribution

on:
  workflow_call:
    inputs:
      aws-domain:
        required: true
        type: string
      aws-domain-owner:
        required: true
        type: string
      aws-role:
        required: true
        type: string
      aws-region:
        required: true
        type: string

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check versioning
        run: |
          poetry_version=$(sed -n 's/^ *version.*=.*"\([^"]*\)".*/\1/p' pyproject.toml) 
          tag_version=${{ github.ref_name }}
          if [ "$poetry_version" != "$tag_version" ]; then
            echo "Poetry version ($poetry_version) and tag ($tag_version) do not match"
            exit 2
          fi
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role }}
      - name: Install dependencies
        run: |
          export POETRY_HTTP_BASIC_CODEARTIFACT_USERNAME=aws
          export POETRY_HTTP_BASIC_CODEARTIFACT_PASSWORD=$(aws codeartifact get-authorization-token --domain-owner ${{ inputs.aws-domain-owner }} --domain ${{ inputs.aws-domain }} --query 'authorizationToken' --output text)
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.create false && poetry install --no-root
      - name: Publish package to CodeArtifact
        run: |
          export POETRY_HTTP_BASIC_CODEARTIFACT_USERNAME=aws
          export POETRY_HTTP_BASIC_CODEARTIFACT_PASSWORD=$(aws codeartifact get-authorization-token --domain-owner ${{ inputs.aws-domain-owner }} --domain ${{ inputs.aws-domain }} --query 'authorizationToken' --output text)
          poetry config repositories.codeartifact https://${{ inputs.aws-domain }}-${{ inputs.aws-domain-owner }}.d.codeartifact.${{ inputs.aws-region }}.amazonaws.com/pypi/api-team/
          poetry config http-basic.codeartifact $POETRY_HTTP_BASIC_CODEARTIFACT_USERNAME $POETRY_HTTP_BASIC_CODEARTIFACT_PASSWORD
          poetry -vvv publish --build --repository codeartifact

permissions:
  id-token: write
  contents: read