name: Build, test and upload

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
      aws-domain:
        required: true
        type: string
      aws-domain-owner:
        required: true
        type: string
      aws-role:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      sonar:
        type: boolean
        required: false
        default: true
      tests:
        type: boolean
        required: false
        default: true
      coverage-xml-location:
        type: string
        required: false
        default: "/usr/src/app/coverage.xml"

permissions:
  id-token: write
  contents: read

jobs:
  build-test-upload:
    name: Build, test and upload new artifact

    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: myn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      REGISTRY: ${{ inputs.registry }}
      REPOSITORY: ${{ inputs.repository }}

    services:
      postgres_main:
        image: postgres:14.5-alpine
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set IMAGE_NAME
        run: |
          GIT_SHORT_REV=$(git rev-parse --short HEAD)
          echo "IMAGE_NAME=$REGISTRY/$REPOSITORY:$GIT_SHORT_REV" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role }}

      - name: Generate CodeArtifact password
        id: codeartifact-password-generator
        run: |
          export CODEARTIFACT_PASSWORD=$(aws codeartifact get-authorization-token --domain-owner ${{ inputs.aws-domain-owner }} --domain ${{ inputs.aws-domain }} --query 'authorizationToken' --output text)
          echo "::add-mask::$CODEARTIFACT_PASSWORD"
          echo "codeartifact_password=$CODEARTIFACT_PASSWORD" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v2
        with:
          context: .
          build-args: POETRY_HTTP_BASIC_CODEARTIFACT_PASSWORD=${{ steps.codeartifact-password-generator.outputs.codeartifact_password }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.IMAGE_NAME }}
          load: true

      - name: Get Python changed files
        id: changed-py-files
        continue-on-error: true
        uses: tj-actions/changed-files@v44
        with:
          files: |
            *.py
            **/*.py
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Run black
        if: steps.changed-py-files.outputs.any_changed == 'true'
        run: |
          docker run --entrypoint "" ${{ env.IMAGE_NAME }} black --target-version py310 -S --check /usr/src/app

      - name: Run tests
        if: inputs.tests
        run: |
          docker run -e "DJANGO_DUMMY_ENV=True" -e POSTGRES_HOST="localhost" \
          -e POSTGRES_PASSWORD -e POSTGRES_DB -e POSTGRES_USER \
          -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN \
          --network="host" --name main_container --user app --entrypoint "" ${{ env.IMAGE_NAME }} docker/test.sh

      - name: Copy coverage.xml
        continue-on-error: true
        run: docker cp main_container:${{ inputs.coverage-xml-location }} ./coverage.xml;

      - name: Sonarqube
        if: ${{ inputs.sonar && (github.actor != 'dependabot[bot]') }}
        uses: sonarsource/sonarqube-scan-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Login to Amazon ECR
        id: login-ecr
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push ${{ env.IMAGE_NAME }} to Amazon ECR
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: docker push ${{ env.IMAGE_NAME }}
