name: Build, test and upload

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
      aws-domain:
        required: true
        type: string
      aws-domain-owner:
        required: true
        type: string
      aws-role:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      sonar:
        type: boolean
        required: false
        default: true
      coverage-xml-location:
        type: string
        required: false
        default: "/home/app/coverage.xml"

permissions:
  id-token: write
  contents: read

jobs:
  build-test-upload:
    name: Build, test and upload new artifact

    runs-on: ubuntu-latest

    env:
      REGISTRY: ${{ inputs.registry }}
      REPOSITORY: ${{ inputs.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set IMAGE_NAME
        run: |
          GIT_SHORT_REV=$(git rev-parse HEAD | cut -c1-7)
          echo "IMAGE_NAME=$REGISTRY/$REPOSITORY:$GIT_SHORT_REV" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role }}

      - name: Generate CodeArtifact password
        id: codeartifact-password-generator
        run: |
          export CODEARTIFACT_PASSWORD=$(aws codeartifact get-authorization-token --domain-owner ${{ inputs.aws-domain-owner }} --domain ${{ inputs.aws-domain }} --query 'authorizationToken' --output text)
          echo "::add-mask::$CODEARTIFACT_PASSWORD"
          echo "codeartifact_password=$CODEARTIFACT_PASSWORD" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          context: .
          build-args: POETRY_HTTP_BASIC_CODEARTIFACT_PASSWORD=${{ steps.codeartifact-password-generator.outputs.codeartifact_password }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.IMAGE_NAME }}
          load: true
          secrets: |
            codeartifact-password=${{ steps.codeartifact-password-generator.outputs.codeartifact_password }}

      - name: Get Python changed files
        id: changed-py-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            *.py
            **/*.py
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Run black
        if: steps.changed-py-files.outputs.any_changed == 'true'
        run: |
          docker run --entrypoint "" ${{ env.IMAGE_NAME }} black --target-version py310 -S --check /usr/src/app

      - name: Run isort
        if: ${{ steps.changed-py-files.outputs.any_changed == 'true' && success() || failure() }}
        run: |
          docker run --entrypoint "" ${{ env.IMAGE_NAME }} isort --check-only --profile black ${{ steps.changed-py-files.outputs.all_changed_files }}

      - name: Run flake8
        if: ${{steps.changed-py-files.outputs.any_changed == 'true' && success() || failure() }}
        run: |
          docker run --entrypoint "" ${{ env.IMAGE_NAME }} flake8 ${{ steps.changed-py-files.outputs.all_changed_files }}

      - name: Run mypy
        if: ${{ steps.changed-py-files.outputs.any_changed == 'true' && success() || failure() }}
        run: |
          docker run --entrypoint "" ${{ env.IMAGE_NAME }} mypy ${{ steps.changed-py-files.outputs.all_changed_files }}

      - name: Run tests
        if: success()
        run: |
          docker compose run --name main_container test tests

      - name: Copy coverage.xml
        continue-on-error: true
        run: docker cp main_container:${{ inputs.coverage-xml-location }} ./coverage.xml;

      - name: Sonarqube
        if: ${{ inputs.sonar && (github.actor != 'dependabot[bot]') }}
        uses: sonarsource/sonarqube-scan-action@v5.0.0
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push ${{ env.IMAGE_NAME }} to Amazon ECR
        run: docker push ${{ env.IMAGE_NAME }}
